### PR TITLE
Initialise

### PR DESCRIPTION
**Pull request by mattgarner**
This app runs fastqc for any number of input fastqs.

The resources directory content was copied directly from dnanexus fastqc app.

Some fastqc options (kmer, adapter seqs etc) are not yet set up, and will be added in a future version.

Example run:
https://platform.dnanexus.com/projects/FqbVv0Q4Y1bQKp69583VJjG3/monitor/job/Fv3KVQ04Y1bb9z2P4xVyvFFJ

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_fastqc/1)

### CODE REVIEW

**Review by Addy81 — CHANGES_REQUESTED** [review]
> Reviewed 259 of 259 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_fastqc/1)* status: all files reviewed, 1 unresolved discussion (waiting on @mattgarner)

___
*[dxapp.json, line 6 at r1](https://reviewable.io/reviews/eastgenomics/eggd_fastqc/1#-MCHLtrj6Emh_sWdXPdj:-MCHLtrj6Emh_sWdXPdk:byo3zeg) ([raw file](https://github.com/eastgenomics/eggd_fastqc/blob/fe8ca18b3e2d943568d284a28741170f9445c479/dxapp.json#L6)):*
> ```JSON
>   "summary": "Runs fastqc once for each input fastq",
>   "dxapi": "1.0.0",
>   "inputSpec": [
> ```

do you need to add a github release version and a version in the app naming?

**Review by Addy81 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_fastqc/1)* status: all files reviewed, 1 unresolved discussion (waiting on @mattgarner)

**Review by mattgarner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_fastqc/1)* status: all files reviewed, 1 unresolved discussion (waiting on @Addy81)

___
*[dxapp.json, line 6 at r1](https://reviewable.io/reviews/eastgenomics/eggd_fastqc/1#-MCHLtrj6Emh_sWdXPdj:-MCHsBvz9bPiOZ4PS9yF:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_fastqc/blob/fe8ca18b3e2d943568d284a28741170f9445c479/dxapp.json#L6)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

do you need to add a github release version and a version in the app naming?
</blockquote></details>

Done.

**Review by Addy81 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_fastqc/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
